---

- name: "Prometheus: checks"
  include: preflight.yml

- block:
    - name: "Prometheus: install"
      include: "install/{{ ansible_distribution }}.yml"

    - name: 'Prometheus: Create systemd service configuration directory'
      file:
        path: /etc/systemd/system/prometheus.service.d
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: "Prometheus: configure systemd service limits"
      ini_file:
        path: /etc/systemd/system/prometheus.service.d/limits.conf
        section: 'Service'
        option: '{{ item.key }}'
        value: '{{ item.value }}'
        backup: true
      with_dict: '{{ prometheus_systemd_limits }}'

    - name: "Prometheus: configure"
      include: "configure.yml"

    - name: "Prometheus: setup netdata"
      template:
        src: netdata.yml.j2
        dest: "{{ prometheus_conf_dir }}/targets/netdata.yml"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
  when: inventory_hostname == prometheus_admin_host

- name: "Prometheus: setup healthchecks"
  include: "healthchecks.yml"
  when: prometheus_blackbox_enabled

- block:
    - name: "Prometheus: (re)start service"
      systemd:
        state: "{{ 'started' if prometheus_provision_only else 'restarted' }}"
        daemon_reload: true
        enabled: "{{ prometheus_systemd_enabled }}"
        name: "prometheus"

    - name: "Prometheus: wait for service to be up"
      wait_for:
        host: "{{ prometheus_listen_ip }}"
        port: "{{ prometheus_listen_port }}"
        delay: 10
  when: inventory_hostname == prometheus_admin_host
...
